from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 60, 400, 400))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.brpkecepatan = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.brpkecepatan.setObjectName("brpkecepatan")
        self.gridLayout.addWidget(self.brpkecepatan, 1, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.Massa = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(100)
        self.Massa.setFont(font)
        self.Massa.setAlignment(QtCore.Qt.AlignCenter)
        self.Massa.setObjectName("Massa")
        self.gridLayout.addWidget(self.Massa, 0, 0, 1, 1)
        self.kecepatan = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(100)
        self.kecepatan.setFont(font)
        self.kecepatan.setAlignment(QtCore.Qt.AlignCenter)
        self.kecepatan.setObjectName("kecepatan")
        self.gridLayout.addWidget(self.kecepatan, 1, 0, 1, 1)
        self.hasil = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(100)
        self.hasil.setFont(font)
        self.hasil.setAlignment(QtCore.Qt.AlignCenter)
        self.hasil.setObjectName("hasil")
        self.gridLayout.addWidget(self.hasil, 3, 0, 1, 1)
        self.brpmassa = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.brpmassa.setTabletTracking(False)
        self.brpmassa.setObjectName("brpmassa")
        self.gridLayout.addWidget(self.brpmassa, 0, 1, 1, 1)
        self.hitung = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(100)
        self.hitung.setFont(font)
        self.hitung.setObjectName("hitung")
        self.gridLayout.addWidget(self.hitung, 2, 1, 1, 1)
        self.hapus = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(100)
        self.hapus.setFont(font)
        self.hapus.setObjectName("hapus")
        self.gridLayout.addWidget(self.hapus, 2, 0, 1, 1)
        self.EnergiKinetik = QtWidgets.QLabel(self.centralwidget)
        self.EnergiKinetik.setGeometry(QtCore.QRect(40, 30, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(100)
        self.EnergiKinetik.setFont(font)
        self.EnergiKinetik.setFrameShape(QtWidgets.QFrame.Box)
        self.EnergiKinetik.setAlignment(QtCore.Qt.AlignCenter)
        self.EnergiKinetik.setObjectName("EnergiKinetik")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 722, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Connect buttons to functions
        self.hitung.clicked.connect(self.hitungEnergiKinetik)
        self.hapus.clicked.connect(self.hapusInput)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kalkulator Energi Kinetik"))
        self.Massa.setText(_translate("MainWindow", "Massa (Kg)"))
        self.kecepatan.setText(_translate("MainWindow", "Kecepatan (m/s)"))
        self.hasil.setText(_translate("MainWindow", "Hasil (Joule)"))
        self.hitung.setText(_translate("MainWindow", "Hitung"))
        self.hapus.setText(_translate("MainWindow", "Hapus"))
        self.EnergiKinetik.setText(_translate("MainWindow", "Energi Kinetik (Ek)"))

    def hitungEnergiKinetik(self):
        try:
            massa = float(self.brpmassa.text())
            kecepatan = float(self.brpkecepatan.text())
            energi_kinetik = 0.5 * massa * (kecepatan * kecepatan)
            self.lineEdit_4.setText(f"{energi_kinetik:.2f}")  # Hasil dalam dua angka desimal
        except ValueError:
            self.lineEdit_4.setText("MASUKAN ANGKA!!!")


    def hapusInput(self):
        self.brpmassa.clear()
        self.brpkecepatan.clear()
        self.lineEdit_4.clear()


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
