# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'glbb.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 50, 400, 250))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.hasil = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.hasil.setObjectName("hasil")
        self.gridLayout.addWidget(self.hasil, 4, 1, 1, 1)
        self.hitung = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hitung.setFont(font)
        self.hitung.setObjectName("hitung")
        self.gridLayout.addWidget(self.hitung, 3, 1, 1, 1)
        self.brpperc = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.brpperc.setObjectName("brpperc")
        self.gridLayout.addWidget(self.brpperc, 1, 1, 1, 1)
        self.brpwaktu = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.brpwaktu.setObjectName("brpwaktu")
        self.gridLayout.addWidget(self.brpwaktu, 2, 1, 1, 1)
        self.hapus = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hapus.setFont(font)
        self.hapus.setObjectName("hapus")
        self.gridLayout.addWidget(self.hapus, 3, 0, 1, 1)
        self.brpkecawal = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.brpkecawal.setObjectName("brpkecawal")
        self.gridLayout.addWidget(self.brpkecawal, 0, 1, 1, 1)
        self.labelkecawal = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelkecawal.setFont(font)
        self.labelkecawal.setAlignment(QtCore.Qt.AlignCenter)
        self.labelkecawal.setObjectName("labelkecawal")
        self.gridLayout.addWidget(self.labelkecawal, 0, 0, 1, 1)
        self.labelpercepatan = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelpercepatan.setFont(font)
        self.labelpercepatan.setAlignment(QtCore.Qt.AlignCenter)
        self.labelpercepatan.setObjectName("labelpercepatan")
        self.gridLayout.addWidget(self.labelpercepatan, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.labelhasil = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelhasil.setFont(font)
        self.labelhasil.setAlignment(QtCore.Qt.AlignCenter)
        self.labelhasil.setObjectName("labelhasil")
        self.gridLayout.addWidget(self.labelhasil, 4, 0, 1, 1)
        
        # Mengubah panjang label judul agar tidak terpotong
        self.judul = QtWidgets.QLabel(self.centralwidget)
        self.judul.setGeometry(QtCore.QRect(30, 19, 500, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.judul.setFont(font)
        self.judul.setAlignment(QtCore.Qt.AlignCenter)
        self.judul.setObjectName("judul")
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 300, 450, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(10, 10, 1800, 118))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Menghubungkan tombol dengan fungsi
        self.hitung.clicked.connect(self.hitung_glbb)
        self.hapus.clicked.connect(self.hapusInput)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.hitung.setText(_translate("MainWindow", "HITUNG"))
        self.hapus.setText(_translate("MainWindow", "HAPUS"))
        self.labelkecawal.setText(_translate("MainWindow", "kecepatan awal (m/s)"))
        self.labelpercepatan.setText(_translate("MainWindow", "percepatan (m/s²)"))
        self.label_5.setText(_translate("MainWindow", "waktu (s) jika ada"))
        self.labelhasil.setText(_translate("MainWindow", "Kecepatan Akhir"))
        self.judul.setText(_translate("MainWindow", "Gerak Lurus Berubah Beraturan (GLBB) Kecepatan Akhir"))
        self.label.setText(_translate("MainWindow", "Note: kosongkan jawaban waktu bila tidak ada"))

    def hitung_glbb(self):
        try:
            percepatan = float(self.brpperc.text())
            kecepatan = float(self.brpkecawal.text())
            waktu_text = self.brpwaktu.text()

            # Jika waktu tidak diisi, hitung jarak dan hasil_notime
            if not waktu_text:
                jarak = (kecepatan ** 2) / (2 * percepatan)
                hasil_notime = (kecepatan ** 2) + (2 * percepatan * jarak)
                self.hasil.setText(f"{hasil_notime ** 0.5:.2f}")  # v adalah akar dari hasil_notime
            else:
                # Jika waktu diisi, gunakan rumus GLBB dengan waktu
                waktu = float(waktu_text)
                hasil_time = kecepatan + (percepatan * waktu)
                self.hasil.setText(f"{hasil_time:.2f}")

        except ValueError:
            self.brpperc.setText("MASUKAN ANGKA!")
            self.brpkecawal.setText("MASUKAN ANGKA!")
            self.brpwaktu.setText("MASUKAN ANGKA!")

    def hapusInput(self):
        self.brpperc.clear()
        self.brpkecawal.clear()
        self.brpwaktu.clear()
        self.hasil.clear()


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
