# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HubunganUsaha.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(722, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 60, 411, 281))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.brpekakhir = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.brpekakhir.setObjectName("brpekakhir")
        self.gridLayout.addWidget(self.brpekakhir, 1, 1, 1, 1)
        self.hasil_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.hasil_2.setObjectName("hasil_2")
        self.gridLayout.addWidget(self.hasil_2, 3, 1, 1, 1)
        self.ekawal = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ekawal.setFont(font)
        self.ekawal.setAlignment(QtCore.Qt.AlignCenter)
        self.ekawal.setObjectName("ekawal")
        self.gridLayout.addWidget(self.ekawal, 0, 0, 1, 1)
        self.ekakhir = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ekakhir.setFont(font)
        self.ekakhir.setAlignment(QtCore.Qt.AlignCenter)
        self.ekakhir.setObjectName("ekakhir")
        self.gridLayout.addWidget(self.ekakhir, 1, 0, 1, 1)
        self.kethasil = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.kethasil.setFont(font)
        self.kethasil.setAlignment(QtCore.Qt.AlignCenter)
        self.kethasil.setObjectName("kethasil")
        self.gridLayout.addWidget(self.kethasil, 3, 0, 1, 1)
        self.brpekawal = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.brpekawal.setTabletTracking(False)
        self.brpekawal.setObjectName("brpekawal")
        self.gridLayout.addWidget(self.brpekawal, 0, 1, 1, 1)
        self.hitung = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hitung.setFont(font)
        self.hitung.setObjectName("hitung")
        self.gridLayout.addWidget(self.hitung, 2, 1, 1, 1)
        self.hapus = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hapus.setFont(font)
        self.hapus.setObjectName("hapus")
        self.gridLayout.addWidget(self.hapus, 2, 0, 1, 1)
        self.EnergiKinetik = QtWidgets.QLabel(self.centralwidget)
        self.EnergiKinetik.setGeometry(QtCore.QRect(40, 30, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.EnergiKinetik.setFont(font)
        self.EnergiKinetik.setFrameShape(QtWidgets.QFrame.Box)
        self.EnergiKinetik.setAlignment(QtCore.Qt.AlignCenter)
        self.EnergiKinetik.setObjectName("EnergiKinetik")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 722, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Menghubungkan tombol dengan fungsi
        self.hitung.clicked.connect(self.hitunghubunganusaha)
        self.hapus.clicked.connect(self.hapusInput)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hubungan Usaha dan Energi Kinetik"))
        self.ekawal.setText(_translate("MainWindow", "Energi kinetik awal (Joule) "))
        self.ekakhir.setText(_translate("MainWindow", "Energi kinetik akhir (Joule) "))
        self.kethasil.setText(_translate("MainWindow", "Usaha (Joule)"))
        self.hitung.setText(_translate("MainWindow", "HITUNG"))
        self.hapus.setText(_translate("MainWindow", "HAPUS"))
        self.EnergiKinetik.setText(_translate("MainWindow", "Hubungan Usaha (W) dan Energi Kinetik"))

    def hitunghubunganusaha(self):
        try:
            ekawal = float(self.brpekawal.text())
            ekakhir = float(self.brpekakhir.text())
            hubunganusaha = ekakhir - ekawal
            self.hasil_2.setText(f"{hubunganusaha:.2f}")  # Hasil dalam dua angka desimal
        except ValueError:
            self.hasil_2.setText("MASUKAN ANGKA!!!")

    def hapusInput(self):
        self.brpekawal.clear()
        self.brpekakhir.clear()
        self.hasil_2.clear()


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
