# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'usaha.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from math import cos, radians
import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(722, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 60, 411, 281))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.brpperpindahan = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.brpperpindahan.setObjectName("brpperpindahan")
        self.gridLayout.addWidget(self.brpperpindahan, 1, 1, 1, 1)
        self.gaya = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gaya.setFont(font)
        self.gaya.setAlignment(QtCore.Qt.AlignCenter)
        self.gaya.setObjectName("gaya")
        self.gridLayout.addWidget(self.gaya, 0, 0, 1, 1)
        self.perpindahan_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.perpindahan_2.setFont(font)
        self.perpindahan_2.setAlignment(QtCore.Qt.AlignCenter)
        self.perpindahan_2.setObjectName("perpindahan_2")
        self.gridLayout.addWidget(self.perpindahan_2, 1, 0, 1, 1)
        self.hasil_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.hasil_2.setObjectName("hasil_2")
        self.gridLayout.addWidget(self.hasil_2, 5, 1, 1, 1)
        self.hapus = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hapus.setFont(font)
        self.hapus.setObjectName("hapus")
        self.gridLayout.addWidget(self.hapus, 4, 0, 1, 1)
        self.kethasil = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.kethasil.setFont(font)
        self.kethasil.setAlignment(QtCore.Qt.AlignCenter)
        self.kethasil.setObjectName("kethasil")
        self.gridLayout.addWidget(self.kethasil, 5, 0, 1, 1)
        self.hitung = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hitung.setFont(font)
        self.hitung.setObjectName("hitung")
        self.gridLayout.addWidget(self.hitung, 4, 1, 1, 1)
        self.brpgaya = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.brpgaya.setTabletTracking(False)
        self.brpgaya.setObjectName("brpgaya")
        self.gridLayout.addWidget(self.brpgaya, 0, 1, 1, 1)
        self.brpderajat = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.brpderajat.setObjectName("brpderajat")
        self.gridLayout.addWidget(self.brpderajat, 2, 1, 1, 1)
        self.sudut = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sudut.setFont(font)
        self.sudut.setAlignment(QtCore.Qt.AlignCenter)
        self.sudut.setObjectName("sudut")
        self.gridLayout.addWidget(self.sudut, 2, 0, 1, 1)
        self.Usaha = QtWidgets.QLabel(self.centralwidget)
        self.Usaha.setGeometry(QtCore.QRect(40, 30, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.Usaha.setFont(font)
        self.Usaha.setFrameShape(QtWidgets.QFrame.Box)
        self.Usaha.setAlignment(QtCore.Qt.AlignCenter)
        self.Usaha.setObjectName("Usaha")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 722, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Menghubungkan tombol dengan fungsi
        self.hitung.clicked.connect(self.hitungusaha)
        self.hapus.clicked.connect(self.hapusInput)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gaya.setText(_translate("MainWindow", "Gaya (Newton, N)"))
        self.perpindahan_2.setText(_translate("MainWindow", "Perpindahan (meter, m)"))
        self.hapus.setText(_translate("MainWindow", "HAPUS"))
        self.kethasil.setText(_translate("MainWindow", "Usaha (Joule)"))
        self.hitung.setText(_translate("MainWindow", "HITUNG"))
        self.sudut.setText(_translate("MainWindow", "Sudut antara gaya"))
        self.Usaha.setText(_translate("MainWindow", "Usaha (W)"))


    
    def hitungusaha(self):
        try:
            gaya = float(self.brpgaya.text())
            perpindahan = float(self.brpperpindahan.text())
            sudut = float(self.brpderajat.text())
            # Konversi sudut dari derajat ke radian
            sudut_radian = radians(sudut)
            usaha = gaya * perpindahan * cos(sudut_radian)
            
            self.hasil_2.setText(f"{usaha:.2f}")  # Hasil dalam dua angka desimal
        except ValueError:
            self.hasil_2.setText("MASUKAN ANGKA!!!")


    def hapusInput(self):
        self.brpgaya.clear()
        self.brpperpindahan.clear()
        self.brpderajat.clear()
        self.hasil_2.clear()




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
