# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'volumesilinder.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import math
import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(722, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 60, 451, 251))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.brptinggi = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.brptinggi.setObjectName("brptinggi")
        self.gridLayout.addWidget(self.brptinggi, 1, 1, 1, 1)
        self.hasil_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.hasil_2.setObjectName("hasil_2")
        self.gridLayout.addWidget(self.hasil_2, 3, 1, 1, 1)
        self.jarijari = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarijari.setFont(font)
        self.jarijari.setAlignment(QtCore.Qt.AlignCenter)
        self.jarijari.setObjectName("jarijari")
        self.gridLayout.addWidget(self.jarijari, 0, 0, 1, 1)
        self.tinggi = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tinggi.setFont(font)
        self.tinggi.setAlignment(QtCore.Qt.AlignCenter)
        self.tinggi.setObjectName("tinggi")
        self.gridLayout.addWidget(self.tinggi, 1, 0, 1, 1)
        self.hasil = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hasil.setFont(font)
        self.hasil.setAlignment(QtCore.Qt.AlignCenter)
        self.hasil.setObjectName("hasil")
        self.gridLayout.addWidget(self.hasil, 3, 0, 1, 1)
        self.brpjarijari = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.brpjarijari.setTabletTracking(False)
        self.brpjarijari.setObjectName("brpjarijari")
        self.gridLayout.addWidget(self.brpjarijari, 0, 1, 1, 1)
        self.hitung = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hitung.setFont(font)
        self.hitung.setObjectName("hitung")
        self.gridLayout.addWidget(self.hitung, 2, 1, 1, 1)
        self.hapus = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hapus.setFont(font)
        self.hapus.setObjectName("hapus")
        self.gridLayout.addWidget(self.hapus, 2, 0, 1, 1)
        self.EnergiKinetik = QtWidgets.QLabel(self.centralwidget)
        self.EnergiKinetik.setGeometry(QtCore.QRect(40, 30, 451, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.EnergiKinetik.setFont(font)
        self.EnergiKinetik.setFrameShape(QtWidgets.QFrame.Box)
        self.EnergiKinetik.setAlignment(QtCore.Qt.AlignCenter)
        self.EnergiKinetik.setObjectName("EnergiKinetik")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 722, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # Menghubungkan tombol dengan fungsi
        self.hitung.clicked.connect(self.hitungvolumesilinder)
        self.hapus.clicked.connect(self.hapusInput)

    

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.jarijari.setText(_translate("MainWindow", "Jari-jari alas (meter, m)"))
        self.tinggi.setText(_translate("MainWindow", "Tinggi silinder (meter, m)"))
        self.hasil.setText(_translate("MainWindow", "Hasil (meter^2)"))
        self.hitung.setText(_translate("MainWindow", "HITUNG"))
        self.hapus.setText(_translate("MainWindow", "HAPUS"))
        self.EnergiKinetik.setText(_translate("MainWindow", "Volume silinder"))

    
    def hitungvolumesilinder(self):
        try:
            tinggi = float(self.brptinggi.text())
            jari_jari = float(self.brpjarijari.text())
            volume_silinder = math.pi * (jari_jari**2) * tinggi
            self.hasil_2.setText(f"{volume_silinder:.2f}")  # Hasil dalam dua angka desimal
        except ValueError:
            self.hasil_2.setText("MASUKAN ANGKA!!!")


    def hapusInput(self):
        self.brpjarijari.clear()
        self.brptinggi.clear()
        self.hasil_2.clear()




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
