# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import math

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(722, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 60, 461, 281))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pkawat = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.pkawat.setObjectName("pkawat")
        self.gridLayout.addWidget(self.pkawat, 1, 1, 1, 1)
        self.hasil_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.hasil_2.setObjectName("hasil_2")
        self.hasil_2.setReadOnly(True)  # Agar hasil tidak bisa diedit
        self.gridLayout.addWidget(self.hasil_2, 3, 1, 1, 1)
        self.jari = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jari.setFont(font)
        self.jari.setAlignment(QtCore.Qt.AlignCenter)
        self.jari.setObjectName("jari")
        self.gridLayout.addWidget(self.jari, 0, 0, 1, 1)
        self.pnjg = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pnjg.setFont(font)
        self.pnjg.setAlignment(QtCore.Qt.AlignCenter)
        self.pnjg.setObjectName("pnjg")
        self.gridLayout.addWidget(self.pnjg, 1, 0, 1, 1)
        self.hasil = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hasil.setFont(font)
        self.hasil.setAlignment(QtCore.Qt.AlignCenter)
        self.hasil.setObjectName("hasil")
        self.gridLayout.addWidget(self.hasil, 3, 0, 1, 1)
        self.jarijari = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.jarijari.setTabletTracking(False)
        self.jarijari.setObjectName("jarijari")
        self.gridLayout.addWidget(self.jarijari, 0, 1, 1, 1)
        self.hitung = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hitung.setFont(font)
        self.hitung.setObjectName("hitung")
        self.gridLayout.addWidget(self.hitung, 2, 1, 1, 1)
        self.hapus = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hapus.setFont(font)
        self.hapus.setObjectName("hapus")
        self.gridLayout.addWidget(self.hapus, 2, 0, 1, 1)
        self.VolumeKawat = QtWidgets.QLabel(self.centralwidget)
        self.VolumeKawat.setGeometry(QtCore.QRect(40, 30, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.VolumeKawat.setFont(font)
        self.VolumeKawat.setFrameShape(QtWidgets.QFrame.Box)
        self.VolumeKawat.setAlignment(QtCore.Qt.AlignCenter)
        self.VolumeKawat.setObjectName("VolumeKawat")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 722, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Connect buttons to functions
        self.hitung.clicked.connect(self.hitungVolumeKawat)
        self.hapus.clicked.connect(self.hapusInput)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kalkulator Volume Kawat"))
        self.jari.setText(_translate("MainWindow", "Jari-Jari (mm)"))
        self.pnjg.setText(_translate("MainWindow", "Panjang Kawat (mm)"))
        self.hasil.setText(_translate("MainWindow", "Hasil (mm^3)"))
        self.hitung.setText(_translate("MainWindow", "HITUNG"))
        self.hapus.setText(_translate("MainWindow", "HAPUS"))
        self.VolumeKawat.setText(_translate("MainWindow", "Volume Kawat"))

    def hitungVolumeKawat(self):
        try:
            jarijari = float(self.jarijari.text())
            pkawat = float(self.pkawat.text())
            volume_kawat = math.pi * (jarijari ** 2) * pkawat
            self.hasil_2.setText(f"{volume_kawat:.2f}")  # Hasil dalam dua angka desimal
        except ValueError:
            self.hasil_2.setText("MASUKAN ANGKA!!!")

    def hapusInput(self):
        self.jarijari.clear()
        self.pkawat.clear()
        self.hasil_2.clear()

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
